prepare:
  split: 0.2

# TODO: Add params for train stage
train_random_forest:
  n_estimators: [100, 150, 200]
  criterion: ['squared_error', 'absolute_error']  # Simplified criterion options for regression
  max_depth: [1, 5, 10]
  min_samples_split: [2, 5]  # Larger value to prevent overfitting
  min_samples_leaf: [1, 3, 5]  # A bit larger for more robustness
  max_features: ['sqrt', 'log2']
  random_state: [42]  # Set a specific seed for reproducibility