name: Maintenance model performance workflow (every 12 hours)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # This line schedules the workflow to run every 12 hours

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pull data with DVC
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GD_CREDENTIALS }}
      run: |
        dvc pull

    - name: Run data Collection
      run: |
        dvc repro collect

    - name: Run data prepare
      run: |
        dvc repro prepare

    - name: Run Model Training
      run: |
        dvc repro train

    - name: Check Model Metrics
      run: |
        dvc repro check_metrics temp.txt

    - name: Check temp.txt content
      id: check_temp
      run: |
        if [[ $(cat temp.txt) == "True" ]]; then
          echo "Temp.txt has True"
          echo "::set-output name=push_to_dvc::true"
        else
          echo "Temp.txt does not have True"
          echo "::set-output name=push_to_dvc::false"
        fi

  push_to_dvc:
    needs: maintenance
    if: ${{ needs.maintenance.outputs.check_temp == 'true' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set Git user information
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
      
    - name: DVC Add and Commit
      run: |
        git add . 
        git commit -m "DVC commit for data file"

    - name: Push data with DVC
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GD_CREDENTIALS }}
      run: |
        dvc push
        git push